name: Deploy ECS Fargate

on:
  push:
    branches:
      - main
      - uat-env
      - test-env

jobs:
  deploy:
    name: Build and Deploy ECS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build, Tag and Push image to ECR
      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_REPO_NAME=ecs-fargate-repo
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$IMAGE_REPO_NAME:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$IMAGE_REPO_NAME:$IMAGE_TAG

      # Step 5: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # Step 6: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 7: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="image_tag=${{ github.sha }}"

      # Step 8: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}"
